"""The application icon and the per-window icons.

Generated by ``tools/make_icons.py`` into ``spwb/resources``, which ships in
the wheel. Two things are worth pinning: that every window actually gets
one - a guarded line repeated five times is how four of them end up without
it - and that each ``.ico`` really carries every size it claims, because a
16 px entry made by shrinking a 256 px one is mush and nothing else would
notice.
"""
import os
import struct

import pytest

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

pytest.importorskip("PySide6")
pytest.importorskip("pyqtgraph")

from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QApplication

from spwb import app_config
from spwb.gui import icons
from spwb.gui.bridge import WindowManager

#: window key -> the class that must carry it
WINDOWS = {
    "tdp": "spwb.gui.time_processing:TimeProcessingWindow",
    "fft": "spwb.gui.fft_analysis:FFTWindow",
    "tf": "spwb.gui.tf_analysis:TransferFunctionWindow",
    "tfa": "spwb.gui.tfa_analysis:TimeFrequencyWindow",
    "lms": "spwb.gui.lms_analysis:LMSWindow",
}

#: what tools/make_icons.py draws into every .ico
EXPECTED_SIZES = {16, 24, 32, 48, 64, 128, 256}


def load(path: str):
    import importlib

    module, name = path.split(":")
    return getattr(importlib.import_module(module), name)


@pytest.fixture(scope="session")
def qapp():
    return QApplication.instance() or QApplication([])


def ico_sizes(path) -> set[int]:
    """The sizes an .ico advertises, read from its directory entries."""
    data = path.read_bytes()
    reserved, kind, count = struct.unpack_from("<HHH", data, 0)
    assert reserved == 0 and kind == 1, f"{path.name} is not an .ico"
    sizes = set()
    for i in range(count):
        width, height = struct.unpack_from("<BB", data, 6 + i * 16)[:2]
        # 0 means 256 in the ICO format, which is why 256 needs the special
        # case rather than overflowing a byte
        sizes.add(width or 256)
        assert (height or 256) == (width or 256), "icons must be square"
    return sizes


# -- the files --------------------------------------------------------------
def test_the_application_icon_exists():
    assert app_config.icon_file() is not None, (
        "run: python tools/make_icons.py")


@pytest.mark.parametrize("key", sorted(WINDOWS))
def test_every_window_type_has_an_icon_file(key):
    assert app_config.window_icon_file(key) is not None


def test_an_unknown_window_key_is_refused():
    with pytest.raises(ValueError, match="unknown window icon"):
        app_config.window_icon_file("nope")


def test_the_keys_match_the_windows():
    assert set(app_config.WINDOW_ICONS) == set(WINDOWS)


@pytest.mark.parametrize("key", sorted(WINDOWS))
def test_each_icon_carries_every_size(key):
    """Drawn per size, not scaled - so all seven must actually be present."""
    assert ico_sizes(app_config.window_icon_file(key)) == EXPECTED_SIZES


def test_the_application_icon_carries_every_size():
    assert ico_sizes(app_config.icon_file()) == EXPECTED_SIZES


def test_the_large_png_for_macos_exists():
    """app_config picks the .png on darwin, so it has to be there."""
    png = app_config.RESOURCES_DIR / "spwb.png"

    assert png.is_file()
    assert QIcon(str(png)).availableSizes(), "unreadable as an icon"


@pytest.mark.parametrize("key", sorted(WINDOWS))
def test_each_icon_loads_and_renders(qapp, key):
    icon = QIcon(str(app_config.window_icon_file(key)))
    available = {size.width() for size in icon.availableSizes()}

    assert available == EXPECTED_SIZES
    for size in (16, 256):
        pixmap = icon.pixmap(size, size)
        assert not pixmap.isNull()
        assert pixmap.width() == size


def test_the_icons_are_not_all_the_same_picture():
    """A copy-paste in the generator would be invisible any other way."""
    seen = {key: app_config.window_icon_file(key).read_bytes()
            for key in WINDOWS}

    assert len(set(seen.values())) == len(WINDOWS)


# -- the windows ------------------------------------------------------------
@pytest.mark.parametrize("key,path", sorted(WINDOWS.items()))
def test_the_window_wears_its_own_icon(qapp, key, path):
    window = load(path)(WindowManager())
    try:
        icon = window.windowIcon()

        assert not icon.isNull(), f"{path} has no window icon"
        # the same artwork the key names, not just any icon
        expected = QIcon(str(app_config.window_icon_file(key)))
        assert (icon.pixmap(64, 64).toImage()
                == expected.pixmap(64, 64).toImage())
    finally:
        window.close()


def test_applying_a_missing_icon_changes_nothing(qapp, monkeypatch):
    """The contract app_config.icon_file has always had: run without one."""
    monkeypatch.setattr(app_config, "window_icon_file", lambda key: None)
    window = load(WINDOWS["fft"])(WindowManager())
    try:
        assert icons.apply_window_icon(window, "fft") is False
    finally:
        window.close()
